# Generated by Django 3.2.7 on 2021-09-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=128, verbose_name='제목'),
        ),
    ]
